# Generated by Django 5.0.6 on 2024-06-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('departament', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('publisher', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.IntegerField(max_length=4)),
                ('number', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
                ('citation', models.CharField(max_length=50)),
                ('pages', models.CharField(max_length=10)),
                ('id_journal', models.CharField(max_length=10)),
            ],
        ),
    ]
