# Generated by Django 5.0.6 on 2024-08-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Departaments',
            new_name='Departament',
        ),
        migrations.RenameModel(
            old_name='Journals',
            new_name='Journal',
        ),
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
    ]
