# Generated by Django 5.0.6 on 2024-08-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0002_rename_authors_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_add_teacher', 'set teacher'),)},
        ),
    ]
