# Generated by Django 4.2.15 on 2024-08-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0004_alter_author_options_alter_author_departament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='job',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='authorofpublication',
            name='id',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departament',
            name='id',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departament',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publisher',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(max_length=20),
        ),
    ]
