# Generated by Django 4.2.15 on 2024-09-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0005_alter_author_id_alter_author_job_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_add_teacher', 'add teacher'), ('can_update_teacher', 'update teacher'))},
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authorofpublication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departament',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
