# Generated by Django 4.2.15 on 2024-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0006_alter_author_options_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(to='PublicationReports.author'),
        ),
        migrations.DeleteModel(
            name='AuthorOfPublication',
        ),
    ]
