# Generated by Django 4.2.15 on 2024-09-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0007_publication_author_delete_authorofpublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
