# Generated by Django 4.2.15 on 2024-09-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0009_alter_journal_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id_journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PublicationReports.journal'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
