# Generated by Django 4.2.15 on 2024-09-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0010_alter_departament_name_alter_publication_citation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
