# Generated by Django 4.2.15 on 2024-09-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0011_alter_publication_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='id_journal',
            new_name='journal',
        ),
    ]
