# Generated by Django 4.2.15 on 2024-09-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0013_remove_publication_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
