# Generated by Django 4.2.15 on 2024-09-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0014_alter_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
