# Generated by Django 4.2.15 on 2024-09-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0015_alter_journal_name_alter_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='citation',
            field=models.IntegerField(null=True),
        ),
    ]
