# Generated by Django 4.2.15 on 2024-09-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0017_book_conference_typeofpublication_publication_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='PublicationReports.typeofpublication'),
        ),
    ]
