# Generated by Django 4.2.15 on 2024-11-08 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationReports', '0019_alter_author_options_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['departament', 'name'], 'permissions': (('can_add_teacher', 'add teacher'), ('can_update_teacher', 'update teacher'))},
        ),
        migrations.AlterField(
            model_name='author',
            name='job',
            field=models.CharField(max_length=500, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=500, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='departament',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Наименование кафедры'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publisher',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PublicationReports.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citation',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Цитирования'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='conference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PublicationReports.conference', verbose_name='Конференция'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PublicationReports.journal', verbose_name='Журнал'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Страницы'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Том'),
        ),
    ]
